# Generated by Django 5.0.3 on 2024-04-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_stock_purchase_price_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="purchase_date",
            field=models.DateField(),
        ),
    ]
